Close #47
Lozovskij/weightlifting_team1 pull request #50
Opened 2020-11-17 17:22 UTC by DmitryAstapchik

2020-11-17 18:03 UTC, Lozovskij requested changes

2020-11-17 18:03 UTC, Lozovskij commented on WeightliftingTeam1/WeightliftingTeam1/Data/SearchResultService.cs
> +            return await Task.Run(() => new List<IGridModel>(attempts));
Can you put it in method for it (like it is in the comments, but it whould be like **HelpSearchForAttempts.GetDataFromDB(request)**)?

2020-11-18 08:22 UTC, DmitryAstapchik commented on WeightliftingTeam1/WeightliftingTeam1/Data/SearchResultService.cs
> +            return await Task.Run(() => new List<IGridModel>(attempts));
ok

2020-11-18 09:15 UTC, Lozovskij approved these changes

2020-11-18 09:15 UTC, merged